### ISSUE TITLE
新账号没有权限

### ISSUE THREAD

**Issue by PoBlue** [PoBlue/review-crawler#2]
除了是 Reviewer 外，其它都没有访问 Review 的权限，应该是最近改版引起的。

更加安全了👍，欲语泪先流，错过良机了。。。。

**Comment by PoBlue** [comment]
1. 解决办法用自己的号去爬（风险极大，随时翻车）不打算用
2. 或者每天自动生成 30 个号用 Chrome 自动打开，Chrome 插件自动爬取数据存储。

嗯。很惨。。看以后还有没有好想法

**Comment by WillBeethoven** [comment]
亮有staff的权限。

**Comment by PoBlue** [comment]
是么，那太好了。只要有一个账号是有 Review 权限的就可以了。开了任意一个项目 Review 权限的。都可以开爬了

@evestorm 借个开了 Review 权限的账号给我用用，我还你一整个 Udacity Review 的信息数据库

可以用我做的这个文件玩一玩，用 Cookie 就可以获取到 Review 信息了，如下图

<img width="846" alt="2017-11-11 9 51 17" src="https://user-images.githubusercontent.com/9304701/32690046-c95dae22-c72a-11e7-9571-ef6516c995f3.png">

**Comment by PoBlue** [comment]
想了下，既然官方都做了这样的限制，应该是之前太多人爬导致服务器的负载过重了。想一想还是不爬了
